/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }








    //////////////////////lab 07:////////////////

    //The users want shops! Create a Shop class; a Shop should have a name, description, and number of dollar signs.
    //Implement a constructor for a Shop.
    //Implement a reasonable toString method for Shops.
    //Add tests for the basics of your Shop class.







//    The users also want to review shops!
//    It would be great if a Review could be about either a Shop or a Restaurant. Choose an implementation, and make
//    this possible.
//    Ensure that your Shop class has an instance method to add a review about that shop, and that it works just as
//    well as the Restaurant instance method with the same purpose.
//    Write tests for this functionality.





}
