/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    //methods form wed. lab and Thurs. part a. lab

    public boolean someLibraryMethod() {
        return true;
    }
}
